name: Publish

on:
  release:
    types: [ published ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: temurin

      - name: Set artifact version
        run: ./mvnw --batch-mode versions:set -DgenerateBackupPoms=falses -DnewVersion=${{ github.event.release.tag_name }}

      - name: Version
        run: |
          cat pom.xml
  update-version:
    needs: [publish]
    permissions:
      contents: write  # for peter-evans/create-pull-request to create branch
      pull-requests: write  # for peter-evans/create-pull-request to create a PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Update pom.xml version
        run: ./mvnw --batch-mode versions:set -DgenerateBackupPoms=false -DnewVersion=${{ github.event.release.tag_name }}

      - name: Update Maven version in readme
        run: sed -i 's/<version>.*<\/version>/<version>${{ github.event.release.tag_name }}<\/version>/g' README.md
        
      - name: Update Maven version in readme
        run: sed -i "s/implementation 'org.sample:demo:.*/implementation 'org.sample:demo:${{ github.event.release.tag_name }}'/g" README.md

      - name: Show diff
        run: git diff

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.2.0
        with:
          commit-message: Update versions to ${{ github.event.release.tag_name }}
          title: Update versions to ${{ github.event.release.tag_name }}
          body: |
            Update versions to ${{ github.event.release.tag_name }}
          branch: update-versions
          reviewers: piotrooo
